version: '3.8'
services:
  servidor_daw:
    image: httpd:alpine
    container_name: daw_app
    volumes:
      - ./app:/usr/local/apache2/htdocs/
    networks:
      red_daw:
        ipv4_address: 172.20.0.10

  proxy:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - servidor_daw
    networks:
      - red_daw

  sftp_server:
    image: atmoz/sftp:alpine
    container_name: daw_sftp
    ports:
      - "2222:22"
    command: deploy_user:Secreta123:::app
    volumes:
      - ./app:/home/deploy_user/app
    networks:
      - red_daw

networks:
  red_daw:
    ipam:
      config:
        - subnet: 172.20.0.0/16