events {
    worker_connections 1024;
}

http {
    # 1. Redirección forzada de HTTP a HTTPS
    server {
        listen 80;
        server_name _;
        return 301 https://$host$request_uri;
    }

    # 2. Servidor HTTPS y Proxy Inverso
    server {
        listen 443 ssl;
        server_name _;

        # Rutas a los certificados que generamos
        ssl_certificate /etc/nginx/certs/nginx.crt;
        ssl_certificate_key /etc/nginx/certs/nginx.key;

        location / {
            # Proxy inverso hacia el puerto interno de la aplicación
            proxy_pass http://daw_app:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}